import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ subsets: ['latin'], weight: ['500', '700'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
      {/* <Script 
        src='scripts/ss.js'
        strategy="afterInteractive"
      /> */}
      <main className={poppins.className}>
       {/* <div className='bg-gradient-to-t from-[#59ab7a] to-[#000000] h-screen'> */}
       <div className='bg-[url("/images/bg2.jpg")] bg-fixed bg-cover'>
        {/*--Container div Started -- */}
        
        {children}

      </div> {/*--Container div Ended -- */}
    </main>
      </body>
    </html>
  )
}